<h2>1. What is the collatz conjecture?</h2>

<p>It is a simple maths equation that is considered is a famous unsolved problem. 
It is a problem that was introduced in 1937 by a German Mathemetician named Lothar Collatz. </p>

<p>Explained: [3] </p>

1.  You start with any positive integer 'n'.
2.  If n is even, you divide it by 2 to get n/2.
3.  if n is odd, mulitplty it by 3 and add 1 to get 3n+1.
4.  Repeat the process indefinitely for the resulting values.

<h2>Python Code for the problem:</h2>

I began by following the source code i found in relation to the code i found online [1]

In [1]:
#This takes an input as an intenger 'n' and generates the 
#The Collatz sequence starting from 'n' 

def collatz_sequence(n):
    sequence = [n] #initilizes a list with the first element being 'n'
    while n != 1: # Loop is entered until n becomes one
        if n % 2 == 0: #if n is even it updates n to n // 2
            n = n // 2
        else: # if its odd then it changes to n = 3*n+1
            n = 3 * n + 1
        sequence.append(n)
    return sequence


# Takes a positive integer 'limit' as an input and verifies
# Collatz conjecture for all numbers from 1 to specificed limit
def verify_collatz_conjecture(limit):
    for i in range(1, limit + 1): # iterates from one to limit
        sequence = collatz_sequence(i) # each i generates the collatz sequence 
        if sequence[-1] != 1: # if last number is not 1, it prints not true
            print(f"Collatz conjecture is not true for {i}: {sequence}")
            return
    print("Collatz conjecture is true for all numbers up to", limit)

# Verify Collatz conjecture for the first 10,000 positive integers
verify_collatz_conjecture(10000)


Collatz conjecture is true for all numbers up to 10000


<p>Breakdown:</p>

1.  I started this solution using the function collatze sequence which takes 'n' which is any integer
2.  I then defined a sequence (as list), which initializes 'n' (the input) as the first element of this list
3.  Then a loop was created the iterate only until 'n' becomes 1.
4.  Within this loop it checks n with 'if' statements, checking wether the number is odd or even, where the different equations will apply. Then the 'n' value is updated into the 'sequence' list.
5.  To verify the collatz conjecture, the input is defined by the limit variable which represents the maximum integer to check
6.  Using a for loop to iterate through the positive numbers, throught to the limit. It then generates the collatz sequence for each i in the range.
7.  If the last integer is not 1, it prints a message stating the collatz sequence is not true
8.  Otherwise it prints true.
9.  Then we call the function.

<h2>2. Square Roots Via Newtons Method</h2>

<h3>What is it?</h3>
<p>When a number is multiplied by itself, it gives the original number, so the square root of 16 is 4, because when you multiply 4 by 4, you get 16.</p>

<h3>Newtons Method for Square roots</h3>

1.  Start with an intial guess of x0 for the root of a function f
2.  Calculate the value of the function and its derivative at x0
3. 


<h2>Python code for Problem [4]</h2>

In [5]:
def sqrt(x):
    # Initial guess for the square root
    z0 = x / 2.0
    # Define the threshold for convergence (where end point meets)
    threshold = 0.01

    while True:
        # Calculate the next guess using the Newton-Raphson formula
        z1 = z0 - (z0 * z0 - x) / (2 * z0)

        # Check if the difference between consecutive guesses is less than the threshold
        if abs(z1 - z0) < threshold:
            return z1  # Return the approximate square root

        # Update the guess for the next iteration
        z0 = z1

# Test the function
x = 9  # Change this to the number for which you want to calculate the square root
approx_sqrt = sqrt(x)
print(f"Approximate square root of {x} is: {approx_sqrt}")


Approximate square root of 9 is: 3.000015360039322


<p>Breakdown</p>

1.  I started the process, after viewing the code i on TutorialsinHand [3] by setting an initial guess 'z0' for the square root, determined as half the value of x.
2.  Then a convergence threshold was created to decide when the end point is met, considering the difference between consecutive guesses to be less than 0.01.
3.  A loop was initialized where each iteration calculated the next guess 'z1' using the Newton-Raphson formula.
4.  The check for convergence was implemented by comparing the differences between 'z1' and 'z0' with the established threshold. If the condition was met, 'z1' was returned as the approximate square root.
5.  In cases where the convergence condition wasn't satisfied, 'z0' was updated with 'z1', and the process continued to the next iteration.
6.  I then set up a sequence (as a list) with 'n' as the first element, and a loop that iterated until 'n' reached 1.
7.  Within the loop, 'if' statements were used to check whether 'n' was odd or even, applying different equations accordingly. The updated 'n' value was then added to the 'sequence' list.
8. Finally, the function was called

<h2>3. Considering all possible functions taking 4 bits as input and outputting 1 single bit</h2>

The inputs are considered as 4 bit computing, as the data or integers are 4 bits wide. So for each input combination as there will be only 1 output, there is 2 possible outputs (0,1). For all input combinations there are 65,536 distinctive functions f: {1,0} -> {0,1} is 2^16 = 65,536, this is because each of the 16 input combinations can independatly map to either 0 or 1, giving 2^16 unique functions. [11]

<p>Breakdown: </p>

1.  I initiated the process by defining a function that takes a 4-bit input named 'input-bits.'
2.  To explore all possible 4-bit input combinations, I employed the itertools.product function, generating a list of tuples, where each tuple represented a distinct 4-bit input combination. With 2 choices (0 or 1) for each of the 4 bits, there were a total of 16 combinations [7] this is expected for certainty 2^4 = 16 .
3.  An empty dictionary, 'function_mapping,' was then created to store the mapping from input combinations to output values.
4.  Utilizing a for loop, I iterated through all possible 4-bit input combinations. For each combination, the random function was invoked with the input to acquire the corresponding output, and this mapping was stored in the 'function_mapping' dictionary.
5.  First the system prints all the functions created, then radomly picks one function from the list.

<h2>Python Code for the problem:</h2>

In [5]:
import itertools
import random

# Define a function that takes a 4-bit input and returns a single bit output
def random_function(input_bits):
    # use the return function to generate a 1 or 0 at random
    return random.choice([0, 1])

# Create a list of all possible 4-bit input combinations
input_combinations = list(itertools.product([0, 1], repeat=4))

# Create a dictionary to store the function mapping
function_mapping = {}

# With use of function mapping where the result is stored, this code iterates over all possible 
# input combinations, using the random function for each one.
for input_bits in input_combinations:
    output = random_function(input_bits)
    function_mapping[input_bits] = output

# Print all function mappings
print("All Function Mappings:")
for input_bits, output in function_mapping.items():
    print(f"Input: {input_bits}, Output: {output}")

# Randomly select and print one function mapping
random_input_bits = random.choice(list(function_mapping.keys()))
random_output = function_mapping[random_input_bits]
print("\nRandomly Selected Function:")
print(f"Input: {random_input_bits}, Output: {random_output}")





All Function Mappings:
Input: (0, 0, 0, 0), Output: 1
Input: (0, 0, 0, 1), Output: 1
Input: (0, 0, 1, 0), Output: 1
Input: (0, 0, 1, 1), Output: 0
Input: (0, 1, 0, 0), Output: 0
Input: (0, 1, 0, 1), Output: 1
Input: (0, 1, 1, 0), Output: 0
Input: (0, 1, 1, 1), Output: 0
Input: (1, 0, 0, 0), Output: 0
Input: (1, 0, 0, 1), Output: 0
Input: (1, 0, 1, 0), Output: 0
Input: (1, 0, 1, 1), Output: 1
Input: (1, 1, 0, 0), Output: 0
Input: (1, 1, 0, 1), Output: 0
Input: (1, 1, 1, 0), Output: 0
Input: (1, 1, 1, 1), Output: 1

Randomly Selected Function:
Input: (1, 1, 0, 1), Output: 0


<h2>4.  Functions that perform multiplcation matrices on two rectangular lists containing floats </h2>

Matrix multiplication is a binary operation that uses pairs of matrices to produce a new matrix. The numebrs within the matrices are multiplid in basic arithmetic, where each column in the first matrix is equal to the number of rows in the second matrix. The resulting matrix will have the same number of rows as the first, and the same number of columns as the second [10].


<p>Breakdown: </p>

1.  Here i began by defining the function for the multiplying of matrixes 'def matrix_multiply' that included 2 matrices as input.
2.  I then converted the input matrices in numpty arrays.
3.  Then i performed the multiplication on the matrices 'using np.dot' this perfroms multiplication on matrices.
4.  I provided samples for demonstration.   
5.  I then return the function as a result that will then print the result of the multiplication between the matrices.

<h2>Code Example in Python: [8] [9]</h2>

In [11]:
import numpy as np

def matrix_multiply(matrix1, matrix2):
    # Convert input matrices to numpy arrays
    matrix1_np = np.array(matrix1)
    matrix2_np = np.array(matrix2)

    # Perform matrix multiplication using numpy's dot function
    result_matrix = np.dot(matrix1_np, matrix2_np)

    return result_matrix

# Example matrices
matrix_A = [
    [1.0, 2.0, 3.0],
    [4.0, 5.0, 6.0],
]

matrix_B = [
    [7.0, 8.0],
    [9.0, 10.0],
    [11.0, 12.0],
]

# Perform matrix multiplication
result = matrix_multiply(matrix_A, matrix_B)

# Print the result
print("Matrix A:")
print(np.array(matrix_A))

print("\nMatrix B:")
print(np.array(matrix_B))

print("\nResultant Matrix:")
print(result)


Matrix A:
[[1. 2. 3.]
 [4. 5. 6.]]

Matrix B:
[[ 7.  8.]
 [ 9. 10.]
 [11. 12.]]

Resultant Matrix:
[[ 58.  64.]
 [139. 154.]]


<h2>Bibliography</h2>

<p>1. Collatz Conjecture</p>

1.  https://www.sanfoundry.com/python-program-test-collatz-conjecture-given-number/ [1]
2.  https://mathworld.wolfram.com/CollatzProblem.html [2]
3.  https://testbook.com/maths/collatz-conjecture#:~:text=The%20History%20Behind%20the%20Collatz,take%20any%20positive%20integer%20n. [3]

<p>2. Square Roots Using Newtons Method</p>

1.  https://tutorialsinhand.com/Articles/python-program-to-find-square-root-of-a-number-using-newton-square-root-formula.aspx [4]
2.  https://en.wikipedia.org/wiki/Newton%27s_method [5]
3.  https://ocw.mit.edu/courses/18-335j-introduction-to-numerical-methods-spring-2019/resources/mit18_335js19_lec1/ [6]

<p>3. All possible functions taking 4 bit inputs and outputting one single bit</p>

1.  https://www.quora.com/Suppose-that-a-logic-gate-has-four-inputs-How-many-possible-input-combinations-must-be-listed-in-its-accompanying-truth-table [7]
2.  https://learn.sparkfun.com/tutorials/logicblocks-experiment-guide/2-3-input-and-gate#:~:text=This%20number%20grows%20exponentially%20at,32%20outputs%2C%20and%20so%20on. [11]

<p>4. Matrice Multiplications on rectangular Lists</p>

1.  https://www.educative.io/blog/numpy-matrix-multiplication [8]
2.  https://www.w3schools.com/python/numpy/default. [9]
3.  https://en.wikipedia.org/wiki/Matrix_multiplication#:~:text=For%20matrix%20multiplication%2C%20the%20number,B%20is%20denoted%20as%20AB. [10]


